#!/bin/bash
# Check if IP of target is entered
if [ -z "$1" ]
 then
    echo "Correct usage is ./nmapcode.sh "
   exit
  else
    echo "Target IP is $1"
    echo "Nmap is running…"
# Run Nmap scan on target and save results to file
    nmap -sV -O $1 > scan_results.txt
    echo "Scan complete, results written to scan_results.txt"
fi
# If the Samba port 445 is found and open, run enum4linux.
if grep 445 scan_results.txt | grep -iq open
  then
    enum4linux -U -S $1 >> scan_results.txt
    echo "Samba found. Enumeration complete."
    echo "Results added to scan_results.txt."
    echo "Open the file to view result."
  else
   echo "SMB share ports not found."
fi
